default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DB_HOST") { "127.0.0.1" } %>
  port: <%= ENV.fetch("DB_PORT") { 7079 } %>
  username: <%= ENV.fetch("DB_USERNAME") { "postgres" } %>
  password: <%= ENV.fetch("DB_PASSWORD") { "password" } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 3 } %>
  min_messages: <%= ENV.fetch("DB_MIN_MESSAGES") { "notice" } %>

development:
  <<: *default
  database: hub_development

test:
  <<: *default
  database: hub_test

production:
  <<: *default
  database: hub
